apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-conf
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.default.svc.cluster.local:9090
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
